const limitNum = 2; // 请求并发数
const ms = 5000; // 错误重试间隔时间
const m_time = 120000; //超时时间
const reNum = 3000; // 重试次数

const depositPath = "F:/download/"; // 储存路径

// 下载页面
const address = [
  ["Hello! Project Digital Books(H!P Digital Books)写真集大全",
    [
      "https://www.tujigu.com/x/51/index_3.html",
      "https://www.tujigu.com/x/51/index_4.html"
    ]
  ]
]

// 历史记录
oldAddress = [
  ["VYJ套图、VISUAL YOUNG JUMP PREMIUM PICTURES写真图片",
    [
      "https://www.tujigu.com/x/36/",
      "https://www.tujigu.com/x/36/index_1.html"
    ]
  ],
  ["超高清Wanibooks官网写真集",
    [
      "https://www.tujigu.com/x/64/",
      "https://www.tujigu.com/x/64/index_1.html",
      "https://www.tujigu.com/x/64/index_2.html"
    ]
  ],
  ["@misty写真集",
    [
      "https://www.tujigu.com/x/65/",
      "https://www.tujigu.com/x/65/index_1.html",
      "https://www.tujigu.com/x/65/index_2.html",
      "https://www.tujigu.com/x/65/index_3.html",
      "https://www.tujigu.com/x/65/index_4.html",
      "https://www.tujigu.com/x/65/index_5.html",
      "https://www.tujigu.com/x/65/index_6.html"
    ]
  ],
  ["Sabra.net写真集图片",
    [
      "https://www.tujigu.com/x/28/",
      "https://www.tujigu.com/x/28/index_1.html",
      "https://www.tujigu.com/x/28/index_2.html",
      "https://www.tujigu.com/x/28/index_3.html",
      "https://www.tujigu.com/x/28/index_4.html",
      "https://www.tujigu.com/x/28/index_5.html",
      "https://www.tujigu.com/x/28/index_6.html",
      "https://www.tujigu.com/x/28/index_7.html"
    ]
  ],
  ["4K-STAR写真套图",
    [
      "https://www.tujigu.com/x/47/",
      "https://www.tujigu.com/x/47/index_1.html",
      "https://www.tujigu.com/x/47/index_2.html",
      "https://www.tujigu.com/x/47/index_3.html",
      "https://www.tujigu.com/x/47/index_4.html",
      "https://www.tujigu.com/x/47/index_5.html",
      "https://www.tujigu.com/x/47/index_6.html",
      "https://www.tujigu.com/x/47/index_7.html",
      "https://www.tujigu.com/x/47/index_8.html"
    ]
  ],
  ["MFStar模范学院写真集图片",
    [
      "https://www.tujigu.com/x/70/",
      "https://www.tujigu.com/x/70/index_1.html",
      "https://www.tujigu.com/x/70/index_2.html",
      "https://www.tujigu.com/x/70/index_3.html",
      "https://www.tujigu.com/x/70/index_4.html",
      "https://www.tujigu.com/x/70/index_5.html",
      "https://www.tujigu.com/x/70/index_6.html",
      "https://www.tujigu.com/x/70/index_7.html",
      "https://www.tujigu.com/x/70/index_8.html",
      "https://www.tujigu.com/x/70/index_9.html"
    ]
  ],
  ["日本DGC官网超高清写真套图",
    [
      "https://www.tujigu.com/x/8/",
      "https://www.tujigu.com/x/8/index_1.html",
      "https://www.tujigu.com/x/8/index_2.html",
      "https://www.tujigu.com/x/8/index_3.html",
      "https://www.tujigu.com/x/8/index_4.html",
      "https://www.tujigu.com/x/8/index_5.html",
      "https://www.tujigu.com/x/8/index_6.html",
      "https://www.tujigu.com/x/8/index_7.html",
      "https://www.tujigu.com/x/8/index_8.html",
      "https://www.tujigu.com/x/8/index_9.html",
      "https://www.tujigu.com/x/8/index_10.html"
    ]
  ],
  ["写真集 [YS Web]",
    [
      "https://www.tujigu.com/x/52/index_11.html",
      "https://www.tujigu.com/x/52/index_12.html",
      "https://www.tujigu.com/x/52/index_13.html",
      "https://www.tujigu.com/x/52/index_14.html",
      "https://www.tujigu.com/x/52/index_15.html"
    ]
  ],
  ["Girlz-High写真集",
    [
      "https://www.tujigu.com/x/79/index_7.html",
      "https://www.tujigu.com/x/79/index_8.html",
      "https://www.tujigu.com/x/79/index_9.html",
      "https://www.tujigu.com/x/79/index_10.html",
      "https://www.tujigu.com/x/79/index_11.html",
      "https://www.tujigu.com/x/79/index_12.html",
      "https://www.tujigu.com/x/79/index_13.html",
      "https://www.tujigu.com/x/79/index_14.html",
      "https://www.tujigu.com/x/79/index_15.html",
      "https://www.tujigu.com/x/79/index_16.html"
    ]
  ],
  ["Imuto.tv写真套图",
    ["https://www.tujigu.com/x/40/",
      "https://www.tujigu.com/x/40/index_1.html"
    ]
  ],
  ["熊川纪信写真集图片",
    ["https://www.tujigu.com/x/16/"]
  ],
  ["Minisuka.tv写真套图",
    ["https://www.tujigu.com/x/35/",
      "https://www.tujigu.com/x/35/index_1.html",
      "https://www.tujigu.com/x/35/index_2.html",
      "https://www.tujigu.com/x/35/index_3.html",
      "https://www.tujigu.com/x/35/index_4.html",
      "https://www.tujigu.com/x/35/index_5.html",
      "https://www.tujigu.com/x/35/index_6.html",
      "https://www.tujigu.com/x/35/index_7.html",
      "https://www.tujigu.com/x/35/index_8.html",
      "https://www.tujigu.com/x/35/index_9.html",
      "https://www.tujigu.com/x/35/index_10.html",
      "https://www.tujigu.com/x/35/index_11.html",
      "https://www.tujigu.com/x/35/index_12.html",
      "https://www.tujigu.com/x/35/index_13.html",
      "https://www.tujigu.com/x/35/index_14.html",
      "https://www.tujigu.com/x/35/index_15.html",
      "https://www.tujigu.com/x/35/index_16.html",
      "https://www.tujigu.com/x/35/index_17.html",
      "https://www.tujigu.com/x/35/index_18.html",
      "https://www.tujigu.com/x/35/index_19.html",
      "https://www.tujigu.com/x/35/index_20.html",
      "https://www.tujigu.com/x/35/index_21.html",
      "https://www.tujigu.com/x/35/index_22.html",
      "https://www.tujigu.com/x/35/index_23.html",
      "https://www.tujigu.com/x/35/index_24.html",
      "https://www.tujigu.com/x/35/index_25.html"
    ]
  ],
  ["Bomb.TV写真集大全",
    ["https://www.tujigu.com/x/50/",
      "https://www.tujigu.com/x/50/index_1.html",
      "https://www.tujigu.com/x/50/index_2.html",
      "https://www.tujigu.com/x/50/index_3.html",
      "https://www.tujigu.com/x/50/index_4.html",
      "https://www.tujigu.com/x/50/index_5.html",
      "https://www.tujigu.com/x/50/index_6.html",
      "https://www.tujigu.com/x/50/index_7.html",
      "https://www.tujigu.com/x/50/index_8.html",
      "https://www.tujigu.com/x/50/index_9.html"
    ]
  ],
  "https://www.tujigu.com/x/95/",
  "https://www.tujigu.com/x/95/index_1.html",
  "https://www.tujigu.com/x/95/index_2.html",
  "https://www.tujigu.com/x/95/index_3.html",
  "https://www.tujigu.com/x/95/index_4.html",
  "https://www.tujigu.com/x/95/index_5.html",
  "https://www.tujigu.com/x/95/index_6.html",
  "https://www.tujigu.com/x/95/index_7.html",
  "https://www.tujigu.com/x/95/index_8.html",
  "https://www.tujigu.com/x/40/",
  "https://www.tujigu.com/x/40/index_1.html",
  "https://www.tujigu.com/x/35/",
  "https://www.tujigu.com/x/35/index_1.html",
  "https://www.tujigu.com/x/35/index_2.html",
  "https://www.tujigu.com/x/35/index_3.html",
  "https://www.tujigu.com/x/35/index_4.html",
  "https://www.tujigu.com/x/35/index_5.html",
  "https://www.tujigu.com/x/35/index_6.html",
  "https://www.tujigu.com/x/35/index_7.html",
  "https://www.tujigu.com/x/35/index_8.html",
  "https://www.tujigu.com/x/35/index_9.html",
  "https://www.tujigu.com/x/35/index_10.html",
  "https://www.tujigu.com/x/35/index_11.html",
  "https://www.tujigu.com/x/35/index_12.html",
  "https://www.tujigu.com/x/35/index_13.html",
  "https://www.tujigu.com/x/35/index_14.html",
  "https://www.tujigu.com/x/35/index_15.html",
  "https://www.tujigu.com/x/35/index_16.html",
  "https://www.tujigu.com/x/35/index_17.html",
  "https://www.tujigu.com/x/35/index_18.html",
  "https://www.tujigu.com/x/35/index_19.html",
  "https://www.tujigu.com/x/35/index_20.html",
  "https://www.tujigu.com/x/35/index_21.html",
  "https://www.tujigu.com/x/35/index_22.html",
  "https://www.tujigu.com/x/35/index_23.html",
  "https://www.tujigu.com/x/35/index_24.html",
  "https://www.tujigu.com/x/35/index_25.html",
  "https://www.tujigu.com/x/50/",
  "https://www.tujigu.com/x/51/",
  "https://www.tujigu.com/x/51/index_1.html",
  "https://www.tujigu.com/x/51/index_2.html",
  "https://www.tujigu.com/x/52/",
  "https://www.tujigu.com/x/52/index_1.html",
  "https://www.tujigu.com/x/52/index_2.html",
  "https://www.tujigu.com/x/52/index_3.html",
  "https://www.tujigu.com/x/52/index_4.html",
  "https://www.tujigu.com/x/52/index_5.html",
  "https://www.tujigu.com/x/52/index_6.html",
  "https://www.tujigu.com/x/52/index_7.html",
  "https://www.tujigu.com/x/52/index_8.html",
  "https://www.tujigu.com/x/52/index_9.html",
  "https://www.tujigu.com/x/52/index_10.html",
  "https://www.tujigu.com/x/33/",
  "https://www.tujigu.com/x/33/index_1.html",
  "https://www.tujigu.com/x/33/index_2.html",
  "https://www.tujigu.com/x/33/index_3.html",
  "https://www.tujigu.com/x/33/index_4.html",
  "https://www.tujigu.com/x/33/index_5.html",
  "https://www.tujigu.com/x/79/",
  "https://www.tujigu.com/x/79/index_1.html",
  "https://www.tujigu.com/x/79/index_2.html",
  "https://www.tujigu.com/x/79/index_3.html",
  "https://www.tujigu.com/x/79/index_4.html",
  "https://www.tujigu.com/x/79/index_5.html",
  "https://www.tujigu.com/x/79/index_6.html",
]

module.exports = {
  depositPath,
  address,
  limitNum,
  ms,
  m_time,
  reNum
}